### ISSUE TITLE
Roadmap for Alpha Release

### ISSUE THREAD

**Issue by sco1** [sco1/flake8-annotations#5]
Now that the metadata experiment is more or less complete, the parsing now needs to be made compatible with flake8

Based on [flake8's plugin development docs](https://flake8.pycqa.org/en/latest/plugin-development/) and looking at some existing flake8 plugins, this seems like the general set of tasks that needs to be done:

- [x] Register checker as a flake8 plugin via setup.py
- [x] Create checker functionality that accepts the AST from flake8 and integrate with existing function metadata walking
- [x] Create an Error object & generate our error codes from what's framed in `error_codes.py` (#10)
- [x] Capture & prioritize Errors before emitting via flake8 (https://github.com/sco1/ast-adventures/issues/9)
- [x] Emit errors to flake8
- [x] Pin dependencies appropriately
- [x] Ensure that the package is pip installable
- [x] Come up with a rock solid package name
